<a href="https://colab.research.google.com/github/Anshulmohan27/Machine_Learning/blob/main/Stellar_Contest_Kaggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [113]:
X_train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [114]:
X_train.head(
)

,id,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population,class
0,0,147.734256,16.959273,25.472123,21.895559,20.357926,19.257113,18.621057,0.408982,M,Red_Sequence,GALAXY
1,1,127.988677,32.346716,20.778509,19.087062,17.587208,17.226067,16.786433,0.157976,M,Red_Sequence,GALAXY
2,2,179.792648,35.344843,21.035203,21.079128,21.171840,20.582629,20.557366,2.823770,O/B,Blue_Cloud,QSO
3,3,225.818295,48.569421,23.305056,21.050736,19.017754,18.365658,17.914952,0.536099,M,Red_Sequence,GALAXY
4,4,141.836135,19.342852,21.703158,19.471680,18.234449,17.899447,17.616185,0.555761,M,Red_Sequence,GALAXY

In [115]:
X_train.isnull().sum()/len(X_train)*100

id                   0.0
alpha                0.0
delta                0.0
u                    0.0
g                    0.0
r                    0.0
i                    0.0
z                    0.0
redshift             0.0
spectral_type        0.0
galaxy_population    0.0
class                0.0
dtype: float64

In [116]:
test.isnull().sum()/len(test)*100

id                   0.0
alpha                0.0
delta                0.0
u                    0.0
g                    0.0
r                    0.0
i                    0.0
z                    0.0
redshift             0.0
spectral_type        0.0
galaxy_population    0.0
dtype: float64

In [117]:
test_id = test['id']

def feature_engineering(df):
    df_copy = df.copy()

    # Drop 'id' column if it exists
    if 'id' in df_copy.columns:
        df_copy = df_copy.drop(columns='id')

    # Columns to apply log transformation
    columns_to_log = ['alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift']

    # Apply log transformation to each column, handling x=0
    for col in columns_to_log:
        if col in df_copy.columns:
            df_copy[col] = df_copy[col].apply(lambda x: np.log(x) if x != 0 else 0)

    return df_copy

# Apply feature engineering to training and test data
X_train = feature_engineering(X_train)
test = feature_engineering(test)

# Separate target variable and drop it from X_train
y_train = X_train['class']
X_train = X_train.drop(columns=['class'])

X_train.head()

,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population
0,4.995415,2.830815,3.237585,3.086284,3.013470,2.957881,2.924293,-0.894083,M,Red_Sequence
1,4.851942,3.476513,3.033919,2.949011,2.867172,2.846424,2.820571,-1.845313,M,Red_Sequence
2,5.191804,3.565152,3.046197,3.048283,3.052672,3.024447,3.023219,1.038073,O/B,Blue_Cloud
3,5.419731,3.882994,3.148670,3.046936,2.945373,2.910483,2.885636,-0.623437,M,Red_Sequence
4,4.954672,2.962323,3.077458,2.968961,2.903313,2.884770,2.868818,-0.587416,M,Red_Sequence

In [118]:
X_train['spectral_type'].value_counts()

spectral_type
M      303323
A/F    122122
G/K    108546
O/B     43356
Name: count, dtype: int64

In [122]:
X_train = pd.get_dummies(X_train, columns=['spectral_type', 'galaxy_population'])
test = pd.get_dummies(test, columns=['spectral_type', 'galaxy_population'])

In [132]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=150,
    max_depth=15,
    min_samples_leaf=5,
    n_jobs=-1,
    random_state=42,
    verbose=100
)

rf.fit(X_train, y_train)
preds = rf.predict(test)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
building tree 1 of 150
building tree 2 of 150
building tree 3 of 150
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    4.4s
building tree 4 of 150[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    5.0s

building tree 5 of 150[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    9.1s

building tree 6 of 150[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    9.6s

building tree 7 of 150[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   15.4s

building tree 8 of 150[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:   16.3s

building tree 9 of 150
[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:   19.6s
building tree 10 of 150[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:   20.8s

building tree 11 of 150[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:   24.1s

building tree 12 of 150[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   26.6s

building tree 13 of 150[Parallel(n_jobs=-1)]: Done  11 tasks      | elapsed:   30.0s

building tree 14 of 150[Parallel(n_jobs=-1)]: Done  12 tasks      | elapsed:   32.0s

building tree 15 of 150[Parallel(n_jobs=-1)]: Done  13 tasks      | elapsed:   35.1s

building tree 16 of 150
[Parallel(n_jobs=-1)]: Done  14 tasks      | elapsed:   36.9s
building tree 17 of 150[Parallel(n_jobs=-1)]: Done  15 tasks      | elapsed:   40.7s

building tree 18 of 150
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:   43.3s
building tree 19 of 150
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   45.5s
building tree 20 of 150[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   48.1s

building tree 21 of 150[Parallel(n_jobs=-1)]: Done  19 tasks      | elapsed:   49.7s

building tree 22 of 150[Parallel(n_jobs=-1)]: Done  20 tasks      | elapsed:   53.1s

building tree 23 of 150[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed:   56.0s

building tree 24 of 150[Parallel(n_jobs=-1)]: Done  22 tasks      | elapsed:   59.3s

building tree 25 of 150[Parallel(n_jobs=-1)]: Done  23 tasks      | elapsed:  1.0min

building tree 26 of 150[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:  1.1min

building tree 27 of 150[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:  1.1min

building tree 28 of 150[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:  1.2min

building tree 29 of 150[Parallel(n_jobs=-1)]: Done  27 tasks      | elapsed:  1.2min

building tree 30 of 150[Parallel(n_jobs=-1)]: Done  28 tasks      | elapsed:  1.2min

building tree 31 of 150[Parallel(n_jobs=-1)]: Done  29 tasks      | elapsed:  1.3min

building tree 32 of 150
[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed:  1.3min
building tree 33 of 150[Parallel(n_jobs=-1)]: Done  31 tasks      | elapsed:  1.4min

building tree 34 of 150[Parallel(n_jobs=-1)]: Done  32 tasks      | elapsed:  1.4min

building tree 35 of 150
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  1.4min
building tree 36 of 150[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:  1.5min

building tree 37 of 150[Parallel(n_jobs=-1)]: Done  35 tasks      | elapsed:  1.5min

building tree 38 of 150[Parallel(n_jobs=-1)]: Done  36 tasks      | elapsed:  1.6min

building tree 39 of 150[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:  1.6min

building tree 40 of 150[Parallel(n_jobs=-1)]: Done  38 tasks      | elapsed:  1.7min

building tree 41 of 150
[Parallel(n_jobs=-1)]: Done  39 tasks      | elapsed:  1.7min
building tree 42 of 150
[Parallel(n_jobs=-1)]: Done  40 tasks      | elapsed:  1.8min
building tree 43 of 150[Parallel(n_jobs=-1)]: Done  41 tasks      | elapsed:  1.8min

building tree 44 of 150[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.9min

building tree 45 of 150[Parallel(n_jobs=-1)]: Done  43 tasks      | elapsed:  1.9min

building tree 46 of 150[Parallel(n_jobs=-1)]: Done  44 tasks      | elapsed:  2.0min

building tree 47 of 150[Parallel(n_jobs=-1)]: Done  45 tasks      | elapsed:  2.0min

building tree 48 of 150
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  2.1min
building tree 49 of 150
[Parallel(n_jobs=-1)]: Done  47 tasks      | elapsed:  2.1min
building tree 50 of 150[Parallel(n_jobs=-1)]: Done  48 tasks      | elapsed:  2.1min

building tree 51 of 150
[Parallel(n_jobs=-1)]: Done  49 tasks      | elapsed:  2.1min
building tree 52 of 150[Parallel(n_jobs=-1)]: Done  50 tasks      | elapsed:  2.2min

building tree 53 of 150
[Parallel(n_jobs=-1)]: Done  51 tasks      | elapsed:  2.2min
building tree 54 of 150[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed:  2.3min

building tree 55 of 150
[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:  2.3min
building tree 56 of 150[Parallel(n_jobs=-1)]: Done  54 tasks      | elapsed:  2.4min

building tree 57 of 150
[Parallel(n_jobs=-1)]: Done  55 tasks      | elapsed:  2.4min
building tree 58 of 150[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:  2.5min

building tree 59 of 150
[Parallel(n_jobs=-1)]: Done  57 tasks      | elapsed:  2.5min
building tree 60 of 150[Parallel(n_jobs=-1)]: Done  58 tasks      | elapsed:  2.6min

building tree 61 of 150[Parallel(n_jobs=-1)]: Done  59 tasks      | elapsed:  2.6min

building tree 62 of 150
[Parallel(n_jobs=-1)]: Done  60 tasks      | elapsed:  2.7min
building tree 63 of 150
[Parallel(n_jobs=-1)]: Done  61 tasks      | elapsed:  2.7min
building tree 64 of 150[Parallel(n_jobs=-1)]: Done  62 tasks      | elapsed:  2.8min

building tree 65 of 150[Parallel(n_jobs=-1)]: Done  63 tasks      | elapsed:  2.8min

building tree 66 of 150
[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:  2.8min
building tree 67 of 150[Parallel(n_jobs=-1)]: Done  65 tasks      | elapsed:  2.9min

building tree 68 of 150[Parallel(n_jobs=-1)]: Done  66 tasks      | elapsed:  2.9min

building tree 69 of 150[Parallel(n_jobs=-1)]: Done  67 tasks      | elapsed:  3.0min

building tree 70 of 150[Parallel(n_jobs=-1)]: Done  68 tasks      | elapsed:  3.0min

building tree 71 of 150[Parallel(n_jobs=-1)]: Done  69 tasks      | elapsed:  3.0min

building tree 72 of 150
[Parallel(n_jobs=-1)]: Done  70 tasks      | elapsed:  3.1min
building tree 73 of 150[Parallel(n_jobs=-1)]: Done  71 tasks      | elapsed:  3.1min

building tree 74 of 150[Parallel(n_jobs=-1)]: Done  72 tasks      | elapsed:  3.2min

building tree 75 of 150[Parallel(n_jobs=-1)]: Done  73 tasks      | elapsed:  3.2min

building tree 76 of 150[Parallel(n_jobs=-1)]: Done  74 tasks      | elapsed:  3.3min

building tree 77 of 150[Parallel(n_jobs=-1)]: Done  75 tasks      | elapsed:  3.3min

building tree 78 of 150[Parallel(n_jobs=-1)]: Done  76 tasks      | elapsed:  3.4min

building tree 79 of 150[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:  3.4min

building tree 80 of 150[Parallel(n_jobs=-1)]: Done  78 tasks      | elapsed:  3.5min

building tree 81 of 150[Parallel(n_jobs=-1)]: Done  79 tasks      | elapsed:  3.5min

building tree 82 of 150[Parallel(n_jobs=-1)]: Done  80 tasks      | elapsed:  3.5min

building tree 83 of 150[Parallel(n_jobs=-1)]: Done  81 tasks      | elapsed:  3.6min

building tree 84 of 150[Parallel(n_jobs=-1)]: Done  82 tasks      | elapsed:  3.6min

building tree 85 of 150[Parallel(n_jobs=-1)]: Done  83 tasks      | elapsed:  3.7min

building tree 86 of 150[Parallel(n_jobs=-1)]: Done  84 tasks      | elapsed:  3.7min

building tree 87 of 150
[Parallel(n_jobs=-1)]: Done  85 tasks      | elapsed:  3.8min
building tree 88 of 150
[Parallel(n_jobs=-1)]: Done  86 tasks      | elapsed:  3.8min
building tree 89 of 150[Parallel(n_jobs=-1)]: Done  87 tasks      | elapsed:  3.8min

building tree 90 of 150[Parallel(n_jobs=-1)]: Done  88 tasks      | elapsed:  3.9min

building tree 91 of 150[Parallel(n_jobs=-1)]: Done  89 tasks      | elapsed:  3.9min

building tree 92 of 150[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:  4.0min

building tree 93 of 150[Parallel(n_jobs=-1)]: Done  91 tasks      | elapsed:  4.0min

building tree 94 of 150[Parallel(n_jobs=-1)]: Done  92 tasks      | elapsed:  4.1min

building tree 95 of 150[Parallel(n_jobs=-1)]: Done  93 tasks      | elapsed:  4.1min

building tree 96 of 150
[Parallel(n_jobs=-1)]: Done  94 tasks      | elapsed:  4.2min
building tree 97 of 150[Parallel(n_jobs=-1)]: Done  95 tasks      | elapsed:  4.2min

building tree 98 of 150[Parallel(n_jobs=-1)]: Done  96 tasks      | elapsed:  4.2min

building tree 99 of 150
[Parallel(n_jobs=-1)]: Done  97 tasks      | elapsed:  4.3min
building tree 100 of 150[Parallel(n_jobs=-1)]: Done  98 tasks      | elapsed:  4.3min

building tree 101 of 150[Parallel(n_jobs=-1)]: Done  99 tasks      | elapsed:  4.4min

building tree 102 of 150[Parallel(n_jobs=-1)]: Done 100 tasks      | elapsed:  4.4min

building tree 103 of 150[Parallel(n_jobs=-1)]: Done 101 tasks      | elapsed:  4.5min

building tree 104 of 150[Parallel(n_jobs=-1)]: Done 102 tasks      | elapsed:  4.5min

building tree 105 of 150[Parallel(n_jobs=-1)]: Done 103 tasks      | elapsed:  4.5min

building tree 106 of 150[Parallel(n_jobs=-1)]: Done 104 tasks      | elapsed:  4.6min

building tree 107 of 150[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:  4.6min

building tree 108 of 150
[Parallel(n_jobs=-1)]: Done 106 tasks      | elapsed:  4.7min
building tree 109 of 150[Parallel(n_jobs=-1)]: Done 107 tasks      | elapsed:  4.7min

building tree 110 of 150[Parallel(n_jobs=-1)]: Done 108 tasks      | elapsed:  4.8min

building tree 111 of 150[Parallel(n_jobs=-1)]: Done 109 tasks      | elapsed:  4.8min

building tree 112 of 150[Parallel(n_jobs=-1)]: Done 110 tasks      | elapsed:  4.9min

building tree 113 of 150
[Parallel(n_jobs=-1)]: Done 111 tasks      | elapsed:  4.9min
building tree 114 of 150
[Parallel(n_jobs=-1)]: Done 112 tasks      | elapsed:  4.9min
building tree 115 of 150
[Parallel(n_jobs=-1)]: Done 113 tasks      | elapsed:  5.0min
building tree 116 of 150[Parallel(n_jobs=-1)]: Done 114 tasks      | elapsed:  5.0min

building tree 117 of 150
[Parallel(n_jobs=-1)]: Done 115 tasks      | elapsed:  5.0min
building tree 118 of 150[Parallel(n_jobs=-1)]: Done 116 tasks      | elapsed:  5.1min

building tree 119 of 150[Parallel(n_jobs=-1)]: Done 117 tasks      | elapsed:  5.1min

building tree 120 of 150[Parallel(n_jobs=-1)]: Done 118 tasks      | elapsed:  5.2min

building tree 121 of 150[Parallel(n_jobs=-1)]: Done 119 tasks      | elapsed:  5.2min

building tree 122 of 150[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:  5.3min

building tree 123 of 150[Parallel(n_jobs=-1)]: Done 121 tasks      | elapsed:  5.3min

building tree 124 of 150
[Parallel(n_jobs=-1)]: Done 122 tasks      | elapsed:  5.4min
building tree 125 of 150
[Parallel(n_jobs=-1)]: Done 123 tasks      | elapsed:  5.4min
building tree 126 of 150[Parallel(n_jobs=-1)]: Done 124 tasks      | elapsed:  5.5min

building tree 127 of 150[Parallel(n_jobs=-1)]: Done 125 tasks      | elapsed:  5.5min

building tree 128 of 150[Parallel(n_jobs=-1)]: Done 126 tasks      | elapsed:  5.5min

building tree 129 of 150[Parallel(n_jobs=-1)]: Done 127 tasks      | elapsed:  5.6min

building tree 130 of 150[Parallel(n_jobs=-1)]: Done 128 tasks      | elapsed:  5.6min

building tree 131 of 150
[Parallel(n_jobs=-1)]: Done 129 tasks      | elapsed:  5.7min
building tree 132 of 150[Parallel(n_jobs=-1)]: Done 130 tasks      | elapsed:  5.7min

building tree 133 of 150[Parallel(n_jobs=-1)]: Done 131 tasks      | elapsed:  5.7min

building tree 134 of 150
[Parallel(n_jobs=-1)]: Done 132 tasks      | elapsed:  5.8min
building tree 135 of 150
[Parallel(n_jobs=-1)]: Done 133 tasks      | elapsed:  5.8min
building tree 136 of 150[Parallel(n_jobs=-1)]: Done 134 tasks      | elapsed:  5.9min

building tree 137 of 150[Parallel(n_jobs=-1)]: Done 135 tasks      | elapsed:  5.9min

building tree 138 of 150[Parallel(n_jobs=-1)]: Done 136 tasks      | elapsed:  6.0min

building tree 139 of 150[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:  6.0min

building tree 140 of 150[Parallel(n_jobs=-1)]: Done 138 tasks      | elapsed:  6.1min

building tree 141 of 150
[Parallel(n_jobs=-1)]: Done 139 tasks      | elapsed:  6.1min
building tree 142 of 150[Parallel(n_jobs=-1)]: Done 140 tasks      | elapsed:  6.1min

building tree 143 of 150
[Parallel(n_jobs=-1)]: Done 141 tasks      | elapsed:  6.2min
building tree 144 of 150[Parallel(n_jobs=-1)]: Done 142 tasks      | elapsed:  6.2min

building tree 145 of 150[Parallel(n_jobs=-1)]: Done 143 tasks      | elapsed:  6.3min

building tree 146 of 150[Parallel(n_jobs=-1)]: Done 144 tasks      | elapsed:  6.3min

building tree 147 of 150[Parallel(n_jobs=-1)]: Done 145 tasks      | elapsed:  6.4min

building tree 148 of 150[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  6.4min

building tree 149 of 150[Parallel(n_jobs=-1)]: Done 147 tasks      | elapsed:  6.4min

building tree 150 of 150
[Parallel(n_jobs=-1)]: Done 150 out of 150 | elapsed:  6.6min finished
[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done   2 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done   3 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done   4 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done   5 tasks      | elapsed:    0.2s
[Parallel(n_jobs=2)]: Done   6 tasks      | elapsed:    0.2s
[Parallel(n_jobs=2)]: Done   7 tasks      | elapsed:    0.2s
[Parallel(n_jobs=2)]: Done   8 tasks      | elapsed:    0.2s
[Parallel(n_jobs=2)]: Done   9 tasks      | elapsed:    0.3s
[Parallel(n_jobs=2)]: Done  10 tasks      | elapsed:    0.3s
[Parallel(n_jobs=2)]: Done  11 tasks      | elapsed:    0.3s
[Parallel(n_jobs=2)]: Done  12 tasks      | elapsed:    0.3s
[Parallel(n_jobs=2)]: Done  13 tasks      | elapsed:    0.4s
[Parallel(n_jobs=2)]: Done  14 tasks      | elapsed:    0.4s
[Parallel(n_jobs=2)]: Done  15 tasks      | elapsed:    0.5s
[Parallel(n_jobs=2)]: Done  16 tasks      | elapsed:    0.5s
[Parallel(n_jobs=2)]: Done  17 tasks      | elapsed:    0.5s
[Parallel(n_jobs=2)]: Done  18 tasks      | elapsed:    0.5s
[Parallel(n_jobs=2)]: Done  19 tasks      | elapsed:    0.6s
[Parallel(n_jobs=2)]: Done  20 tasks      | elapsed:    0.6s
[Parallel(n_jobs=2)]: Done  21 tasks      | elapsed:    0.6s
[Parallel(n_jobs=2)]: Done  22 tasks      | elapsed:    0.6s
[Parallel(n_jobs=2)]: Done  23 tasks      | elapsed:    0.7s
[Parallel(n_jobs=2)]: Done  24 tasks      | elapsed:    0.7s
[Parallel(n_jobs=2)]: Done  25 tasks      | elapsed:    0.7s
[Parallel(n_jobs=2)]: Done  26 tasks      | elapsed:    0.7s
[Parallel(n_jobs=2)]: Done  27 tasks      | elapsed:    0.8s
[Parallel(n_jobs=2)]: Done  28 tasks      | elapsed:    0.8s
[Parallel(n_jobs=2)]: Done  29 tasks      | elapsed:    0.8s
[Parallel(n_jobs=2)]: Done  30 tasks      | elapsed:    0.8s
[Parallel(n_jobs=2)]: Done  31 tasks      | elapsed:    0.9s
[Parallel(n_jobs=2)]: Done  32 tasks      | elapsed:    0.9s
[Parallel(n_jobs=2)]: Done  33 tasks      | elapsed:    0.9s
[Parallel(n_jobs=2)]: Done  34 tasks      | elapsed:    1.0s
[Parallel(n_jobs=2)]: Done  35 tasks      | elapsed:    1.0s
[Parallel(n_jobs=2)]: Done  36 tasks      | elapsed:    1.0s
[Parallel(n_jobs=2)]: Done  37 tasks      | elapsed:    1.1s
[Parallel(n_jobs=2)]: Done  38 tasks      | elapsed:    1.1s
[Parallel(n_jobs=2)]: Done  39 tasks      | elapsed:    1.1s
[Parallel(n_jobs=2)]: Done  40 tasks      | elapsed:    1.1s
[Parallel(n_jobs=2)]: Done  41 tasks      | elapsed:    1.2s
[Parallel(n_jobs=2)]: Done  42 tasks      | elapsed:    1.2s
[Parallel(n_jobs=2)]: Done  43 tasks      | elapsed:    1.2s
[Parallel(n_jobs=2)]: Done  44 tasks      | elapsed:    1.3s
[Parallel(n_jobs=2)]: Done  45 tasks      | elapsed:    1.3s
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    1.3s
[Parallel(n_jobs=2)]: Done  47 tasks      | elapsed:    1.4s
[Parallel(n_jobs=2)]: Done  48 tasks      | elapsed:    1.4s
[Parallel(n_jobs=2)]: Done  49 tasks      | elapsed:    1.4s
[Parallel(n_jobs=2)]: Done  50 tasks      | elapsed:    1.4s
[Parallel(n_jobs=2)]: Done  51 tasks      | elapsed:    1.5s
[Parallel(n_jobs=2)]: Done  52 tasks      | elapsed:    1.5s
[Parallel(n_jobs=2)]: Done  53 tasks      | elapsed:    1.5s
[Parallel(n_jobs=2)]: Done  54 tasks      | elapsed:    1.6s
[Parallel(n_jobs=2)]: Done  55 tasks      | elapsed:    1.6s
[Parallel(n_jobs=2)]: Done  56 tasks      | elapsed:    1.6s
[Parallel(n_jobs=2)]: Done  57 tasks      | elapsed:    1.6s
[Parallel(n_jobs=2)]: Done  58 tasks      | elapsed:    1.7s
[Parallel(n_jobs=2)]: Done  59 tasks      | elapsed:    1.7s
[Parallel(n_jobs=2)]: Done  60 tasks      | elapsed:    1.7s
[Parallel(n_jobs=2)]: Done  61 tasks      | elapsed:    1.8s
[Parallel(n_jobs=2)]: Done  62 tasks      | elapsed:    1.8s
[Parallel(n_jobs=2)]: Done  63 tasks      | elapsed:    1.8s
[Parallel(n_jobs=2)]: Done  64 tasks      | elapsed:    1.8s
[Parallel(n_jobs=2)]: Done  65 tasks      | elapsed:    1.9s
[Parallel(n_jobs=2)]: Done  66 tasks      | elapsed:    1.9s
[Parallel(n_jobs=2)]: Done  67 tasks      | elapsed:    1.9s
[Parallel(n_jobs=2)]: Done  68 tasks      | elapsed:    1.9s
[Parallel(n_jobs=2)]: Done  69 tasks      | elapsed:    2.0s
[Parallel(n_jobs=2)]: Done  70 tasks      | elapsed:    2.0s
[Parallel(n_jobs=2)]: Done  71 tasks      | elapsed:    2.0s
[Parallel(n_jobs=2)]: Done  72 tasks      | elapsed:    2.1s
[Parallel(n_jobs=2)]: Done  73 tasks      | elapsed:    2.1s
[Parallel(n_jobs=2)]: Done  74 tasks      | elapsed:    2.1s
[Parallel(n_jobs=2)]: Done  75 tasks      | elapsed:    2.2s
[Parallel(n_jobs=2)]: Done  76 tasks      | elapsed:    2.2s
[Parallel(n_jobs=2)]: Done  77 tasks      | elapsed:    2.2s
[Parallel(n_jobs=2)]: Done  78 tasks      | elapsed:    2.3s
[Parallel(n_jobs=2)]: Done  79 tasks      | elapsed:    2.3s
[Parallel(n_jobs=2)]: Done  80 tasks      | elapsed:    2.3s
[Parallel(n_jobs=2)]: Done  81 tasks      | elapsed:    2.3s
[Parallel(n_jobs=2)]: Done  82 tasks      | elapsed:    2.4s
[Parallel(n_jobs=2)]: Done  83 tasks      | elapsed:    2.4s
[Parallel(n_jobs=2)]: Done  84 tasks      | elapsed:    2.4s
[Parallel(n_jobs=2)]: Done  85 tasks      | elapsed:    2.5s
[Parallel(n_jobs=2)]: Done  86 tasks      | elapsed:    2.5s
[Parallel(n_jobs=2)]: Done  87 tasks      | elapsed:    2.5s
[Parallel(n_jobs=2)]: Done  88 tasks      | elapsed:    2.5s
[Parallel(n_jobs=2)]: Done  89 tasks      | elapsed:    2.6s
[Parallel(n_jobs=2)]: Done  90 tasks      | elapsed:    2.6s
[Parallel(n_jobs=2)]: Done  91 tasks      | elapsed:    2.6s
[Parallel(n_jobs=2)]: Done  92 tasks      | elapsed:    2.6s
[Parallel(n_jobs=2)]: Done  93 tasks      | elapsed:    2.7s
[Parallel(n_jobs=2)]: Done  94 tasks      | elapsed:    2.7s
[Parallel(n_jobs=2)]: Done  95 tasks      | elapsed:    2.7s
[Parallel(n_jobs=2)]: Done  96 tasks      | elapsed:    2.8s
[Parallel(n_jobs=2)]: Done  97 tasks      | elapsed:    2.8s
[Parallel(n_jobs=2)]: Done  98 tasks      | elapsed:    2.8s
[Parallel(n_jobs=2)]: Done  99 tasks      | elapsed:    2.9s
[Parallel(n_jobs=2)]: Done 100 tasks      | elapsed:    2.9s
[Parallel(n_jobs=2)]: Done 101 tasks      | elapsed:    2.9s
[Parallel(n_jobs=2)]: Done 102 tasks      | elapsed:    2.9s
[Parallel(n_jobs=2)]: Done 103 tasks      | elapsed:    3.0s
[Parallel(n_jobs=2)]: Done 104 tasks      | elapsed:    3.0s
[Parallel(n_jobs=2)]: Done 105 tasks      | elapsed:    3.0s
[Parallel(n_jobs=2)]: Done 106 tasks      | elapsed:    3.0s
[Parallel(n_jobs=2)]: Done 107 tasks      | elapsed:    3.1s
[Parallel(n_jobs=2)]: Done 108 tasks      | elapsed:    3.1s
[Parallel(n_jobs=2)]: Done 109 tasks      | elapsed:    3.2s
[Parallel(n_jobs=2)]: Done 110 tasks      | elapsed:    3.2s
[Parallel(n_jobs=2)]: Done 111 tasks      | elapsed:    3.2s
[Parallel(n_jobs=2)]: Done 112 tasks      | elapsed:    3.2s
[Parallel(n_jobs=2)]: Done 113 tasks      | elapsed:    3.3s
[Parallel(n_jobs=2)]: Done 114 tasks      | elapsed:    3.3s

In [133]:
print(preds)

['GALAXY' 'GALAXY' 'GALAXY' ... 'GALAXY' 'QSO' 'GALAXY']

In [134]:
preds.shape

(247435,)

In [130]:
test.shape

(247435, 14)

In [135]:
sub = pd.DataFrame(
    {
        'id': test_id,
        'class': preds
    }
)

sub.to_csv('submission.csv', index=False)